### PR TITLE
add typescript definition.

### PR DESCRIPTION
**Pull request by septs**

### CODE REVIEW

**Comment by septs** [comment]
@colbyfayock request merge.

**Comment by colbyfayock** [comment]
hey @septs im not experienced with TS yet but this is looking good to me. i  gave a try running https://github.com/microsoft/dtslint on it for my own sanity and seemed to work just fine

thanks for adding this!

**Comment by colbyfayock** [comment]
@all-contributors please add @septs for code

**Comment by septs** [comment]
@colbyfayock next release date? (npm)

**Comment by colbyfayock** [comment]
@septs forgot to push that out - it should be available now at `0.6.1`

**Pull request merged**
