### PR TITLE
Added String[] type for template_filename + tests

### PR DESCRIPTION
**Pull request by superelement**
Added 'string array' type for 'template_filename' option, so you can easily pass an array of pages for a single partial.

### CODE REVIEW

**Comment by colbyfayock** [comment]
@superelement this looks great. thanks for the thorough PR with the tests and such 👏

just published 0.5.4  🎉

**Comment by superelement** [comment]
Happy to help. Thanks for the quick response.

**Comment by jamesonhill** [comment]
Should this work for subdirectory file names? I'm having issues where it seems the partial is not being injected when I do `template_filename: ['/someSubDir/index.html']`

**Comment by jamesonhill** [comment]
Ha, nevermind I forgot to update the package. Disregard.

**Pull request merged**
